name: ğŸ³

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      groups: ${{ steps.config.outputs.matrix }}
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v4
      - id: config
        run: deno run --allow-net --allow-read --allow-write --allow-env src/main.ts

  builds:
    name: ğŸ·ï¸ ${{ matrix.name }}
    needs:
      - setup
    uses: ./.github/workflows/build-group.yml
    strategy:
      matrix:
        include: ${{ fromJson(needs.setup.outputs.groups) }}
      fail-fast: false
    with:
      tasks: ${{ toJson(matrix.tasks) }}
      push: ${{ github.ref == 'refs/heads/master' || github.event_name == 'schedule' }}
      manifests: ${{ matrix.manifests }}
    secrets: inherit